"""Rebuild the script/style block in index.html and demo.html: every module preloaded, and every file address
stamped with a fingerprint of its contents (e.g. js/picks.js?v=3f9a1c2e).

    python3 scripts/stamp.py           # update both pages; run before every push that touches js/ or css/
    python3 scripts/stamp.py --check   # only report; exits 1 if a page is out of date

Why: GitHub Pages lets browsers keep each file for 10 minutes. Without fingerprints, a browser can pair a new
module with an older cached copy of another one, and the page stops at "Loading the slate…". A changed file gets a
new address, so it's always fetched fresh; unchanged files keep theirs and stay cached.

How: an import map points each module's plain address (./js/picks.js) at its stamped one, so the modules' own
`import ... from './picks.js'` lines don't change. Preloads let the browser fetch every module at once instead
of discovering them one level at a time.
"""
import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
START, END = "<!-- build:assets -->", "<!-- /build:assets -->"
PAGES = {"index.html": [], "demo.html": ["js/demo-live.js"]}   # extra entry scripts per page, loaded before main.js


def modules(entry):
    seen = []

    def walk(f):
        f = f.resolve()
        if f in seen:
            return
        seen.append(f)
        for m in re.findall(r"^import .*? from '(\.[^']+)';", f.read_text(), re.M):
            walk(f.parent / m)

    walk(ROOT / entry)
    return [str(f.relative_to(ROOT)) for f in seen]


def stamp(path):
    return f"{path}?v={hashlib.sha1((ROOT / path).read_bytes()).hexdigest()[:8]}"


def block(extra):
    mods = sorted(set(modules("js/main.js")) | set(extra))
    imap = json.dumps({"imports": {f"./{m}": f"./{stamp(m)}" for m in mods}}, indent=1)
    lines = [
        START,
        "<!-- Generated by scripts/stamp.py (run it after changing any file in js/ or css/); don't edit by hand. -->",
        f'<script type="importmap">\n{imap}\n</script>',
        f'<link rel="stylesheet" href="{stamp("css/app.css")}">',
        *[f'<script type="module" src="{stamp(e)}"></script>' for e in extra],
        f'<script type="module" src="{stamp("js/main.js")}"></script>',
        *[f'<link rel="modulepreload" href="{stamp(m)}">' for m in mods if m != "js/main.js" and m not in extra],
        END,
    ]
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv
    stale = []
    for page, extra in PAGES.items():
        p = ROOT / page
        html = p.read_text()
        if START not in html or END not in html:
            sys.exit(f"{page}: missing the {START} ... {END} markers")
        a, b = html.index(START), html.index(END) + len(END)
        new = html[:a] + block(extra) + html[b:]
        if new != html:
            stale.append(page)
            if not check:
                p.write_text(new)
    if check:
        print(f"out of date: {', '.join(stale)} (run python3 scripts/stamp.py)" if stale else "up to date")
        sys.exit(1 if stale else 0)
    print(f"updated: {', '.join(stale)}" if stale else "already up to date")


if __name__ == "__main__":
    main()
